apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foo-bar-service-monitor
  namespace: kewl-ns
spec:
  jobLabel: foo-bar
  selector:
    matchLabels:
      app: foo-bar
  namespaceSelector:
    any: true
  endpoints:
  - port: fizz
    path: /buzz/foo-bar
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
    interval: 60s
    scrapeTimeout: 30s
